import csv
import json
import os
import pandas as pd
import fitz

# Define data structure for pages 2 & 3 (PDF pages 6 & 7)
p2_p3_data = [
    # Item 1 - Book Page 2 (PDF Page 6)
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 1, "Dhivehi_Word": "eba", "English_Gloss": "there", "POS": "ADV", "Grammar_Analysis": "LOC.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 2, "Dhivehi_Word": "uḷē", "English_Gloss": "lives", "POS": "VERB", "Grammar_Analysis": "LOC.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 3, "Dhivehi_Word": "eba", "English_Gloss": "there", "POS": "ADV", "Grammar_Analysis": "PRS.3SG.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 4, "Dhivehi_Word": "uḷē", "English_Gloss": "lives", "POS": "VERB", "Grammar_Analysis": "OBL.SG.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 5, "Dhivehi_Word": "fiñdanfuḷakā", "English_Gloss": "a f.-bird", "POS": "NOUN", "Grammar_Analysis": "SOC.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 6, "Dhivehi_Word": "boḍanfuḷek", "English_Gloss": "and a b.-bird", "POS": "CONJ", "Grammar_Analysis": "NOM.SG.", "Full_Sentence": "eba uḷē eba uḷē fiñdanfuḷakā boḍanfuḷek.", "English_Sentence_Translation": "Somewhere, there live a fiñdanā-bird and a boñdanā-bird."},

    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 1, "Dhivehi_Word": "fiñdanā", "English_Gloss": "the f.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.DEF.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 2, "Dhivehi_Word": "bō", "English_Gloss": "head", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 3, "Dhivehi_Word": "ebege", "English_Gloss": "he lived", "POS": "VERB", "Grammar_Analysis": "PT.IV.3SG.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 4, "Dhivehi_Word": "boñdanā", "English_Gloss": "the b.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.DEF.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 5, "Dhivehi_Word": "bō", "English_Gloss": "head", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 6, "Dhivehi_Word": "ebege", "English_Gloss": "he lived", "POS": "VERB", "Grammar_Analysis": "PT.IV.3SG.", "Full_Sentence": "fiñdanā bō ebege boñdanā bō ebege.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there)."},

    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 1, "Dhivehi_Word": "fiñdanu", "English_Gloss": "f.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 2, "Dhivehi_Word": "ebege", "English_Gloss": "he lived", "POS": "VERB", "Grammar_Analysis": "PT.3SG.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 3, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 4, "Dhivehi_Word": "boñdanu", "English_Gloss": "b.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 5, "Dhivehi_Word": "ebege", "English_Gloss": "he lived", "POS": "VERB", "Grammar_Analysis": "PT.3SG.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},
    {"Item_ID": "1", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 6, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "fiñdanu ebege-ai boñdanu ebege-ai.", "English_Sentence_Translation": "A fiñdanā-bird lived (there) and a boñdanā-bird lived (there), they say."},

    # Item 2 - Book Page 2 (PDF Page 6)
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 1, "Dhivehi_Word": "ge", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "OBL.SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 2, "Dhivehi_Word": "eḍan", "English_Gloss": "to build", "POS": "VERB", "Grammar_Analysis": "INF.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 3, "Dhivehi_Word": "boñdanfuḷu", "English_Gloss": "the b.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 4, "Dhivehi_Word": "aḷafi", "English_Gloss": "he built", "POS": "VERB", "Grammar_Analysis": "PT.I.3SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 5, "Dhivehi_Word": "hai", "English_Gloss": "teak", "POS": "NOUN", "Grammar_Analysis": "ATTR.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 6, "Dhivehi_Word": "vakaru", "English_Gloss": "wood", "POS": "NOUN", "Grammar_Analysis": "ABL.SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 7, "Dhivehi_Word": "fiñdanfuḷu", "English_Gloss": "the f.-bird", "POS": "NOUN", "Grammar_Analysis": "NOM.SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 8, "Dhivehi_Word": "aḷafi", "English_Gloss": "he built", "POS": "VERB", "Grammar_Analysis": "PT.I.3SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 9, "Dhivehi_Word": "fī", "English_Gloss": "rotten", "POS": "ADJ", "Grammar_Analysis": "ATTR.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 10, "Dhivehi_Word": "lieśi", "English_Gloss": "brushwood", "POS": "NOUN", "Grammar_Analysis": "ABL.SG.", "Full_Sentence": "ge eḍan boñdanfuḷu aḷafi hai vakaru; fidanfuḷu aḷafi fī lieśi.", "English_Sentence_Translation": "As time went by, the f.-bird built a house from rotten brushwood, the b.-bird built a house all from timber."},

    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 1, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 2, "Dhivehi_Word": "eḍāś", "English_Gloss": "to build", "POS": "VERB", "Grammar_Analysis": "INF.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 3, "Dhivehi_Word": "vakara", "English_Gloss": "wood", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 4, "Dhivehi_Word": "kaṇḍāś", "English_Gloss": "to cut", "POS": "VERB", "Grammar_Analysis": "INF.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 5, "Dhivehi_Word": "gosfei", "English_Gloss": "having gone", "POS": "VERB", "Grammar_Analysis": "ABS.I", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 6, "Dhivehi_Word": "boñdanā", "English_Gloss": "the b.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.DEF.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 7, "Dhivehi_Word": "keṇḍī", "English_Gloss": "what it cut was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 8, "Dhivehi_Word": "hai", "English_Gloss": "teak", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 9, "Dhivehi_Word": "vakara", "English_Gloss": "wood", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 10, "Dhivehi_Word": "fiñdanā", "English_Gloss": "the f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.DEF.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 11, "Dhivehi_Word": "keṇḍī", "English_Gloss": "what it cut was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 12, "Dhivehi_Word": "fī", "English_Gloss": "rotten", "POS": "ADJ", "Grammar_Analysis": "PART.PT.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 13, "Dhivehi_Word": "lieśi", "English_Gloss": "brushwood", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gē eḍāś vakara kaṇḍāś gosfei boñdanā keṇḍī hai vakara fiñdanā keṇḍī fī lieśi.", "English_Sentence_Translation": "Having gone to cut wood for building the house, the b.-bird cut teak wood (while) the f.-bird cut rotten brushwood."},

    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 1, "Dhivehi_Word": "gohofē", "English_Gloss": "having gone", "POS": "VERB", "Grammar_Analysis": "ABS.I", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 2, "Dhivehi_Word": "fiñdanu", "English_Gloss": "f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 3, "Dhivehi_Word": "keṇḍī", "English_Gloss": "what he cut was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 4, "Dhivehi_Word": "fī", "English_Gloss": "rotten", "POS": "ADJ", "Grammar_Analysis": "PART.PT.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 5, "Dhivehi_Word": "lieśi", "English_Gloss": "brushwood", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 6, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 7, "Dhivehi_Word": "boñdanu", "English_Gloss": "b.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 8, "Dhivehi_Word": "keṇḍī", "English_Gloss": "what he cut was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 9, "Dhivehi_Word": "hai", "English_Gloss": "all", "POS": "PRON", "Grammar_Analysis": "ATTR.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 10, "Dhivehi_Word": "vakaro", "English_Gloss": "timber", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},
    {"Item_ID": "2", "Book_Page": 2, "PDF_Page": 6, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 11, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "gohofē fiñdanu keṇḍī fī lieśi-ai, boñdanu keṇḍī hai vakar-ai.", "English_Sentence_Translation": "Having gone, the f.-bird cut rotten brushwood (while) the b.-bird cut all timber."},

    # Item 3 - Book Page 3 (PDF Page 7)
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 1, "Dhivehi_Word": "kaṇḍagen", "English_Gloss": "cutting", "POS": "VERB", "Grammar_Analysis": "ABS.III", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 2, "Dhivehi_Word": "ās", "English_Gloss": "coming", "POS": "VERB", "Grammar_Analysis": "ABS.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 3, "Dhivehi_Word": "de", "English_Gloss": "two", "POS": "CARD", "Grammar_Analysis": "ATTR.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 4, "Dhivehi_Word": "verie", "English_Gloss": "people", "POS": "NOUN", "Grammar_Analysis": "NOM.PL.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 5, "Dhivehi_Word": "de", "English_Gloss": "two", "POS": "CARD", "Grammar_Analysis": "ATTR.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 6, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 7, "Dhivehi_Word": "eḍafie", "English_Gloss": "they built", "POS": "VERB", "Grammar_Analysis": "PT.I.3PL.", "Full_Sentence": "kaṇḍagen ās de verie de gē eḍafie.", "English_Sentence_Translation": "Having come back from cutting (wood), they built their two houses."},

    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 1, "Dhivehi_Word": "fiñdanu", "English_Gloss": "f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 2, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 3, "Dhivehi_Word": "eḍī", "English_Gloss": "where he built was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 4, "Dhivehi_Word": "raḷo", "English_Gloss": "wave", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 5, "Dhivehi_Word": "jahā", "English_Gloss": "hitting", "POS": "VERB", "Grammar_Analysis": "PART.PRS.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 6, "Dhivehi_Word": "faśi", "English_Gloss": "beginning (place)", "POS": "NOUN", "Grammar_Analysis": "LOC.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},
    {"Item_ID": "3", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 7, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "fiñdanu gē eḍī raḷo jahā faśi-ai.", "English_Sentence_Translation": "The f.-bird built his house at the place just where the waves reach."},

    # Item 3a - Book Page 3 (PDF Page 7)
    {"Item_ID": "3a", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 1, "Dhivehi_Word": "boṇḍanu", "English_Gloss": "b.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "boṇḍanu gē eḍī eggami-ai.", "English_Sentence_Translation": "The b.-bird built his house inside the land."},
    {"Item_ID": "3a", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 2, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "boṇḍanu gē eḍī eggami-ai.", "English_Sentence_Translation": "The b.-bird built his house inside the land."},
    {"Item_ID": "3a", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 3, "Dhivehi_Word": "eḍī", "English_Gloss": "where he built was", "POS": "VERB", "Grammar_Analysis": "PART.PT.+FOC.", "Full_Sentence": "boṇḍanu gē eḍī eggami-ai.", "English_Sentence_Translation": "The b.-bird built his house inside the land."},
    {"Item_ID": "3a", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 4, "Dhivehi_Word": "eggami", "English_Gloss": "within the populated area", "POS": "NOUN", "Grammar_Analysis": "LOC.", "Full_Sentence": "boṇḍanu gē eḍī eggami-ai.", "English_Sentence_Translation": "The b.-bird built his house inside the land."},
    {"Item_ID": "3a", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 5, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "boṇḍanu gē eḍī eggami-ai.", "English_Sentence_Translation": "The b.-bird built his house inside the land."},

    # Item 4 - Book Page 3 (PDF Page 7)
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 1, "Dhivehi_Word": "aḷaigen", "English_Gloss": "Having built", "POS": "VERB", "Grammar_Analysis": "ABS.III", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 2, "Dhivehi_Word": "uḷeni", "English_Gloss": "living", "POS": "VERB", "Grammar_Analysis": "PART.PRS.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 3, "Dhivehi_Word": "koś", "English_Gloss": "making", "POS": "VERB", "Grammar_Analysis": "ABS.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 4, "Dhivehi_Word": "ek", "English_Gloss": "one", "POS": "CARD", "Grammar_Analysis": "ATTR.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 5, "Dhivehi_Word": "reaku", "English_Gloss": "in night", "POS": "NOUN", "Grammar_Analysis": "OBL.SG.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 6, "Dhivehi_Word": "ai", "English_Gloss": "having come", "POS": "VERB", "Grammar_Analysis": "PART.PT.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 7, "Dhivehi_Word": "vilāgaḍeggai", "English_Gloss": "in a rain cloud", "POS": "NOUN", "Grammar_Analysis": "LOC.SG.INDEF.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 8, "Dhivehi_Word": "fiñdanfuḷu", "English_Gloss": "f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.SG.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 9, "Dhivehi_Word": "ge", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.SG.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 10, "Dhivehi_Word": "veṭṭijje", "English_Gloss": "collapsed", "POS": "VERB", "Grammar_Analysis": "PT.IV.3SG.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Male'", "Dialect_Code": "M", "Word_Index": 11, "Dhivehi_Word": "eve", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "aḷaigen uḷeni koś ek reaku ai vilāgaḍeggai fiñdanfuḷu ge veṭṭijje eve.", "English_Sentence_Translation": "After having built (the houses) and having lived on (like this), in a rain shower which had come one night, the f.-bird’s house collapsed."},

    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 1, "Dhivehi_Word": "ek", "English_Gloss": "one", "POS": "CARD", "Grammar_Analysis": "ATTR.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 2, "Dhivehi_Word": "reaki", "English_Gloss": "at a night", "POS": "NOUN", "Grammar_Analysis": "LOC.INDEF.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 3, "Dhivehi_Word": "gada", "English_Gloss": "strong", "POS": "ADJ", "Grammar_Analysis": "ATTR.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 4, "Dhivehi_Word": "vissāra", "English_Gloss": "rain", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 5, "Dhivehi_Word": "āsei", "English_Gloss": "coming", "POS": "VERB", "Grammar_Analysis": "ABS.I", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 6, "Dhivehi_Word": "fiñdanā", "English_Gloss": "the f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.DEF.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 7, "Dhivehi_Word": "fī", "English_Gloss": "rotten", "POS": "ADJ", "Grammar_Analysis": "PART.PT.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 8, "Dhivehi_Word": "lieśin", "English_Gloss": "from brushwood", "POS": "NOUN", "Grammar_Analysis": "ABL.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 9, "Dhivehi_Word": "eḍi", "English_Gloss": "built", "POS": "VERB", "Grammar_Analysis": "PART.PT.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 10, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Addu", "Dialect_Code": "A", "Word_Index": 11, "Dhivehi_Word": "uduhige", "English_Gloss": "it flew up", "POS": "VERB", "Grammar_Analysis": "PT.IV.3SG.", "Full_Sentence": "ek reaki gada vissāra āsei fiñdanā fī lieśin eḍi gē uduhige.", "English_Sentence_Translation": "One night, when a heavy rain came, the house the f.-bird had built with rotten brushwood flew away."},

    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 1, "Dhivehi_Word": "fiñdanu", "English_Gloss": "f.-bird", "POS": "NOUN", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 2, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 3, "Dhivehi_Word": "eḍāgen", "English_Gloss": "having built", "POS": "VERB", "Grammar_Analysis": "ABS.III", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 4, "Dhivehi_Word": "nidanna", "English_Gloss": "to sleep", "POS": "VERB", "Grammar_Analysis": "INF.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 5, "Dhivehi_Word": "ot", "English_Gloss": "being", "POS": "VERB", "Grammar_Analysis": "PART.PRS.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 6, "Dhivehi_Word": "vēlai", "English_Gloss": "at time", "POS": "NOUN", "Grammar_Analysis": "LOC.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 7, "Dhivehi_Word": "raḷo", "English_Gloss": "wave", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 8, "Dhivehi_Word": "jahā", "English_Gloss": "hitting", "POS": "VERB", "Grammar_Analysis": "ABS.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 9, "Dhivehi_Word": "miu", "English_Gloss": "this one's", "POS": "DPRON", "Grammar_Analysis": "OBL.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 10, "Dhivehi_Word": "bolaha", "English_Gloss": "to head", "POS": "NOUN", "Grammar_Analysis": "DAT.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 11, "Dhivehi_Word": "gē", "English_Gloss": "house", "POS": "NOUN", "Grammar_Analysis": "NOM.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 12, "Dhivehi_Word": "veṭṭīge", "English_Gloss": "fell", "POS": "VERB", "Grammar_Analysis": "PT.IV.3SG.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."},
    {"Item_ID": "4", "Book_Page": 3, "PDF_Page": 7, "Dialect": "Fua Mulaku", "Dialect_Code": "F", "Word_Index": 13, "Dhivehi_Word": "ai", "English_Gloss": "they say", "POS": "QPARTC", "Grammar_Analysis": "EXT.", "Full_Sentence": "fiñdanu gē eḍāgen nidanna ot vēlai raḷo jahā miu bolaha gē veṭṭīge-ai.", "English_Sentence_Translation": "When the f.-bird was about to sleep after having built his house, a wave struck and so the house fell on his head."}
]

df_p2_p3 = pd.DataFrame(p2_p3_data)

# Save CSV
csv_p2_p3_path = "files/dhivehi_dialect_story_words_page_2_3.csv"
df_p2_p3.to_csv(csv_p2_p3_path, index=False, encoding="utf-8-sig")

# Save JSON
json_p2_p3_path = "files/dhivehi_dialect_story_words_page_2_3.json"
with open(json_p2_p3_path, "w", encoding="utf-8") as f:
    json.dump(p2_p3_data, f, ensure_ascii=False, indent=2)

# Generate Markdown file
md_p2_p3_path = "files/dhivehi_dialect_story_words_page_2_3.md"
with open(md_p2_p3_path, "w", encoding="utf-8") as f:
    f.write("# Dhivehi Dialect Word Extraction - Story T1 (Book Pages 2 & 3 / PDF Pages 6 & 7)\n\n")
    f.write("This table extracts every Dhivehi word, its dialect variant, English gloss, Part of Speech (POS), grammatical tag, full sentence context, and sentence-level English translation from Sonja Fritz (2002), *The Dhivehi Language*, Vol II: Materials.\n\n")
    f.write("## Dialect Color Shading Key\n")
    f.write("- **Male' (M)**: Light Grey\n")
    f.write("- **Addu (A)**: Medium Grey\n")
    f.write("- **Fua Mulaku (F)**: Darker Grey\n\n")
    f.write("## Word Alignment Table (Book Pages 2 & 3)\n\n")
    f.write(df_p2_p3.to_markdown(index=False))
    f.write("\n\n---\n*Extracted from PDF Pages 6 & 7 (Book Pages 2 & 3)*\n")

print(f"Page 2 & 3 extraction saved: {csv_p2_p3_path}, {json_p2_p3_path}, {md_p2_p3_path}")
